version: '3.1'

services:
  snw:
    image: spring-native-webflux:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    environment:
      spring.data.mongodb.uri: mongodb://root:example@mongo:27017
    depends_on:
      - mongo
      - mongo-express
